export enum ApplicationStatus {
  NOT_APPLIED = 'NOT_APPLIED',
  REGISTERED = 'REGISTERED',
  FINALIST = 'FINALIST',
  CONFIRMED = 'CONFIRMED',
  DECLINED = 'DECLINED',
  NOT_SELECTED = 'NOT_SELECTED',
}
