export enum HibiscusRole {
  SUPERADMIN = 'SUPERADMIN',
  TEAM_MEMBER = 'TEAM MEMBER',
  SPONSOR = 'SPONSOR',
  VOLUNTEER = 'VOLUNTEER',
  HACKER = 'HACKER',
  APPLICANT = 'APPLICANT',
  JUDGE = 'JUDGE',
  FINALIST = 'FINALIST',
}
